language: scala

scala:
  - 2.11.12
  - 2.12.7
  - 2.13.0-M5

jdk:
  - oraclejdk8

sudo: false

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt

script:
  - sbt ++$TRAVIS_SCALA_VERSION -Dfile.encoding=UTF8 test mimaReportBinaryIssues

